Portfolio-details-popup-window-pull-request
UsamaMasood12/Portfolio_1 pull request #1
Opened 2022-12-20 19:59 UTC by UsamaMasood12

In this project, I added the popup window of the detail section of the project with the help of Js code.

2022-12-20 20:26 UTC, emmiiorji requested changes
Hi @UsamaMasood12, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![A little bit more](https://user-images.githubusercontent.com/20554583/208759602-973291f7-5722-4097-91e5-074c35db7272.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 20:26 UTC, emmiiorji commented on index.js
> +}
As a best practice in JavaScript, a forEach loop is preferred over the conventional for loop especially when the sample size is not considered large. This is for better readability.

With a forEach loop, the above code could be `PROJECTS_INFO.forEach((project) => {createProjectCard(project)})`

2022-12-20 20:26 UTC, emmiiorji commented on index.js
> +function CreateProjectCard(project_info) {
As is the convention in JavaScript, kindly modify the name of the function to have a camelCase.

2022-12-20 20:26 UTC, emmiiorji commented on index.js
> +    */
To make the code base concise, kindly remove unused pieces of code.

2022-12-21 08:24 UTC, Owusu-Desmond approved these changes
Hi @UsamaMasood12 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3ohs7IyTLZ1lfV64zS/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-21 08:26 UTC, merged